export const listall = [
  {
    id: 1000052,
    version: 9,
    compNameCn: 'Precision Shipping Inc.',
    compNameEn: 'Test123',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000017,
    version: 25,
    compNameCn: '广州润通国际货运有限公司深圳分公司',
    countryId: 1,
    cityId: 2882,
    cityNameCn: '深圳',
    cityNameEn: 'Shenzhen',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000019,
    version: 20,
    compNameCn: '上海盟捷国际货运有限公司',
    compNameEn: 'ShanghaiJiemnghuoyun1111',
    countryId: 1,
    cityId: 2668,
    cityNameCn: '秦皇岛',
    cityNameEn: 'Qinhuangdao',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008371,
    version: 6,
    compNameCn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    compNameEn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    countryId: 149,
    cityId: 538,
    cityNameCn: '汉堡',
    cityNameEn: 'Hamburg',
    countryNameCn: '德国',
    countryNameEn: 'Germany',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000319,
    version: 16,
    compNameEn: 'Farway Express International Logistics (Shanghai) Co.,Ltd',
    countryId: 145,
    cityId: 329,
    cityNameCn: '安特卫普',
    cityNameEn: 'Antwerp',
    countryNameCn: '比利时',
    countryNameEn: 'Belgium',
    relSaleId: 160,
    relSaleName: '许娜(Freya)',
    belongDepartmentId: 40,
    belongDepartmentName: '海外销售四部二组',
    customerId: 277,
    customerName: '王鹤曈(teresa)',
    customerDepartmentId: 27,
    customerDepartmentName: '海外客户成功部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007441,
    version: 17,
    compNameCn: 'ceshi999公司',
    compNameEn: 'ceshi999',
    countryId: 1,
    cityId: 2667,
    cityNameCn: '唐山',
    cityNameEn: 'Tangshan',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008291,
    version: 24,
    compNameEn: 'Atlanta',
    countryId: 68,
    cityId: 99,
    cityNameCn: '阿布扎比',
    cityNameEn: 'Abu Dhabi',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000135,
    version: 38,
    compNameCn: '深圳市中技物流有限公司',
    compNameEn: 'Sinotech Logistics Co.,Ltd.',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 200,
    relSaleName: '蒙文雅',
    belongDepartmentId: 42,
    belongDepartmentName: '国内销售二区',
    customerId: 178,
    customerName: '翁婷婷',
    customerDepartmentId: 28,
    customerDepartmentName: '国内会员服务部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1004187,
    version: 15,
    compNameCn: '上海邦达天原货运有限公司芜湖分公司',
    compNameEn: 'Shanghai Air Sea Transport Inc. Wuhu Branch Ltd.',
    countryId: 1,
    cityId: 2779,
    cityNameCn: '芜湖',
    cityNameEn: 'Wuhu',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007362,
    version: 51,
    compNameCn: '中文公司',
    compNameEn: 'jiekou0',
    countryId: 2,
    cityId: 315,
    cityNameCn: '阿黎博里',
    cityNameEn: 'Alibori',
    countryNameCn: '贝宁',
    countryNameEn: 'Benin',
    relSaleId: 297,
    relSaleName: '李小鑫',
    belongDepartmentId: 43,
    belongDepartmentName: '国内销售一部',
    customerId: 265,
    customerName: '张彬',
    customerDepartmentId: 44,
    customerDepartmentName: '国内销售三部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000929,
    version: 7,
    compNameEn: 'southward intl logistics ltd.',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007697,
    version: 10,
    compNameEn: 'Los Angeles Limited Technology',
    countryId: 167,
    cityId: 3609,
    cityNameCn: '纽约',
    cityNameEn: 'New York',
    countryNameCn: '美国',
    countryNameEn: 'United States',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007747,
    version: 9,
    compNameEn: 'wybtest',
    countryId: 68,
    cityId: 101,
    cityNameCn: '迪拜',
    cityNameEn: 'Dubai',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 2057668,
    version: 12,
    compNameCn: '浙江中外运有限公司宁波明州分公司',
    compNameEn: 'SINOTRANS ZHEJIANG CO.,LTD. NINGBO MINGZHOU BRANCH',
    countryId: 1,
    cityId: 2768,
    cityNameCn: '宁波',
    cityNameEn: 'Ningbo',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 192,
    relSaleName: '刘帅(Brook)',
    belongDepartmentId: 44,
    belongDepartmentName: '国内销售三部',
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3008252,
    version: 8,
    compNameCn: '大连其味无穷恶趣味',
    compNameEn: 'hwreg28 comp',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 307,
    relSaleName: 'admin3',
    belongDepartmentId: 20,
    belongDepartmentName: '测试组',
    customerId: 310,
    customerName: 'admin6-ldy(ldy)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008646,
    version: 1,
    compNameCn: '入到算有限责任公司',
    compNameEn: 'jiao202306090928',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008647,
    version: 2,
    compNameCn: '实些红有限责任公司',
    compNameEn: 'jiao202306090954',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008650,
    version: 3,
    compNameCn: '各化音有限责任公司',
    compNameEn: 'jiao202306091034',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008656,
    version: 1,
    compNameEn: 'jiao202306090337',
    countryId: 51,
    cityId: 14,
    cityNameCn: '阿尔及尔',
    cityNameEn: 'Algiers',
    countryNameCn: '阿尔及利亚',
    countryNameEn: 'Algeria',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008721,
    version: 1,
    compNameCn: 'adsfasfdsaf',
    compNameEn: 'adsfasfdsaf',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 333,
    customerName: '测试账号_llj(TEST_LLJ)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 1000052,
    version: 9,
    compNameCn: 'Precision Shipping Inc.',
    compNameEn: 'Test123',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000017,
    version: 25,
    compNameCn: '广州润通国际货运有限公司深圳分公司',
    countryId: 1,
    cityId: 2882,
    cityNameCn: '深圳',
    cityNameEn: 'Shenzhen',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000019,
    version: 20,
    compNameCn: '上海盟捷国际货运有限公司',
    compNameEn: 'ShanghaiJiemnghuoyun1111',
    countryId: 1,
    cityId: 2668,
    cityNameCn: '秦皇岛',
    cityNameEn: 'Qinhuangdao',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008371,
    version: 6,
    compNameCn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    compNameEn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    countryId: 149,
    cityId: 538,
    cityNameCn: '汉堡',
    cityNameEn: 'Hamburg',
    countryNameCn: '德国',
    countryNameEn: 'Germany',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000319,
    version: 16,
    compNameEn: 'Farway Express International Logistics (Shanghai) Co.,Ltd',
    countryId: 145,
    cityId: 329,
    cityNameCn: '安特卫普',
    cityNameEn: 'Antwerp',
    countryNameCn: '比利时',
    countryNameEn: 'Belgium',
    relSaleId: 160,
    relSaleName: '许娜(Freya)',
    belongDepartmentId: 40,
    belongDepartmentName: '海外销售四部二组',
    customerId: 277,
    customerName: '王鹤曈(teresa)',
    customerDepartmentId: 27,
    customerDepartmentName: '海外客户成功部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007441,
    version: 17,
    compNameCn: 'ceshi999公司',
    compNameEn: 'ceshi999',
    countryId: 1,
    cityId: 2667,
    cityNameCn: '唐山',
    cityNameEn: 'Tangshan',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008291,
    version: 24,
    compNameEn: 'Atlanta',
    countryId: 68,
    cityId: 99,
    cityNameCn: '阿布扎比',
    cityNameEn: 'Abu Dhabi',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000135,
    version: 38,
    compNameCn: '深圳市中技物流有限公司',
    compNameEn: 'Sinotech Logistics Co.,Ltd.',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 200,
    relSaleName: '蒙文雅',
    belongDepartmentId: 42,
    belongDepartmentName: '国内销售二区',
    customerId: 178,
    customerName: '翁婷婷',
    customerDepartmentId: 28,
    customerDepartmentName: '国内会员服务部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1004187,
    version: 15,
    compNameCn: '上海邦达天原货运有限公司芜湖分公司',
    compNameEn: 'Shanghai Air Sea Transport Inc. Wuhu Branch Ltd.',
    countryId: 1,
    cityId: 2779,
    cityNameCn: '芜湖',
    cityNameEn: 'Wuhu',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007362,
    version: 51,
    compNameCn: '中文公司',
    compNameEn: 'jiekou0',
    countryId: 2,
    cityId: 315,
    cityNameCn: '阿黎博里',
    cityNameEn: 'Alibori',
    countryNameCn: '贝宁',
    countryNameEn: 'Benin',
    relSaleId: 297,
    relSaleName: '李小鑫',
    belongDepartmentId: 43,
    belongDepartmentName: '国内销售一部',
    customerId: 265,
    customerName: '张彬',
    customerDepartmentId: 44,
    customerDepartmentName: '国内销售三部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000929,
    version: 7,
    compNameEn: 'southward intl logistics ltd.',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007697,
    version: 10,
    compNameEn: 'Los Angeles Limited Technology',
    countryId: 167,
    cityId: 3609,
    cityNameCn: '纽约',
    cityNameEn: 'New York',
    countryNameCn: '美国',
    countryNameEn: 'United States',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007747,
    version: 9,
    compNameEn: 'wybtest',
    countryId: 68,
    cityId: 101,
    cityNameCn: '迪拜',
    cityNameEn: 'Dubai',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 2057668,
    version: 12,
    compNameCn: '浙江中外运有限公司宁波明州分公司',
    compNameEn: 'SINOTRANS ZHEJIANG CO.,LTD. NINGBO MINGZHOU BRANCH',
    countryId: 1,
    cityId: 2768,
    cityNameCn: '宁波',
    cityNameEn: 'Ningbo',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 192,
    relSaleName: '刘帅(Brook)',
    belongDepartmentId: 44,
    belongDepartmentName: '国内销售三部',
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3008252,
    version: 8,
    compNameCn: '大连其味无穷恶趣味',
    compNameEn: 'hwreg28 comp',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 307,
    relSaleName: 'admin3',
    belongDepartmentId: 20,
    belongDepartmentName: '测试组',
    customerId: 310,
    customerName: 'admin6-ldy(ldy)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008646,
    version: 1,
    compNameCn: '入到算有限责任公司',
    compNameEn: 'jiao202306090928',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008647,
    version: 2,
    compNameCn: '实些红有限责任公司',
    compNameEn: 'jiao202306090954',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008650,
    version: 3,
    compNameCn: '各化音有限责任公司',
    compNameEn: 'jiao202306091034',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008656,
    version: 1,
    compNameEn: 'jiao202306090337',
    countryId: 51,
    cityId: 14,
    cityNameCn: '阿尔及尔',
    cityNameEn: 'Algiers',
    countryNameCn: '阿尔及利亚',
    countryNameEn: 'Algeria',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008721,
    version: 1,
    compNameCn: 'adsfasfdsaf',
    compNameEn: 'adsfasfdsaf',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 333,
    customerName: '测试账号_llj(TEST_LLJ)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 1000052,
    version: 9,
    compNameCn: 'Precision Shipping Inc.',
    compNameEn: 'Test123',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000017,
    version: 25,
    compNameCn: '广州润通国际货运有限公司深圳分公司',
    countryId: 1,
    cityId: 2882,
    cityNameCn: '深圳',
    cityNameEn: 'Shenzhen',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000019,
    version: 20,
    compNameCn: '上海盟捷国际货运有限公司',
    compNameEn: 'ShanghaiJiemnghuoyun1111',
    countryId: 1,
    cityId: 2668,
    cityNameCn: '秦皇岛',
    cityNameEn: 'Qinhuangdao',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008371,
    version: 6,
    compNameCn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    compNameEn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    countryId: 149,
    cityId: 538,
    cityNameCn: '汉堡',
    cityNameEn: 'Hamburg',
    countryNameCn: '德国',
    countryNameEn: 'Germany',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000319,
    version: 16,
    compNameEn: 'Farway Express International Logistics (Shanghai) Co.,Ltd',
    countryId: 145,
    cityId: 329,
    cityNameCn: '安特卫普',
    cityNameEn: 'Antwerp',
    countryNameCn: '比利时',
    countryNameEn: 'Belgium',
    relSaleId: 160,
    relSaleName: '许娜(Freya)',
    belongDepartmentId: 40,
    belongDepartmentName: '海外销售四部二组',
    customerId: 277,
    customerName: '王鹤曈(teresa)',
    customerDepartmentId: 27,
    customerDepartmentName: '海外客户成功部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007441,
    version: 17,
    compNameCn: 'ceshi999公司',
    compNameEn: 'ceshi999',
    countryId: 1,
    cityId: 2667,
    cityNameCn: '唐山',
    cityNameEn: 'Tangshan',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008291,
    version: 24,
    compNameEn: 'Atlanta',
    countryId: 68,
    cityId: 99,
    cityNameCn: '阿布扎比',
    cityNameEn: 'Abu Dhabi',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000135,
    version: 38,
    compNameCn: '深圳市中技物流有限公司',
    compNameEn: 'Sinotech Logistics Co.,Ltd.',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 200,
    relSaleName: '蒙文雅',
    belongDepartmentId: 42,
    belongDepartmentName: '国内销售二区',
    customerId: 178,
    customerName: '翁婷婷',
    customerDepartmentId: 28,
    customerDepartmentName: '国内会员服务部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1004187,
    version: 15,
    compNameCn: '上海邦达天原货运有限公司芜湖分公司',
    compNameEn: 'Shanghai Air Sea Transport Inc. Wuhu Branch Ltd.',
    countryId: 1,
    cityId: 2779,
    cityNameCn: '芜湖',
    cityNameEn: 'Wuhu',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007362,
    version: 51,
    compNameCn: '中文公司',
    compNameEn: 'jiekou0',
    countryId: 2,
    cityId: 315,
    cityNameCn: '阿黎博里',
    cityNameEn: 'Alibori',
    countryNameCn: '贝宁',
    countryNameEn: 'Benin',
    relSaleId: 297,
    relSaleName: '李小鑫',
    belongDepartmentId: 43,
    belongDepartmentName: '国内销售一部',
    customerId: 265,
    customerName: '张彬',
    customerDepartmentId: 44,
    customerDepartmentName: '国内销售三部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000929,
    version: 7,
    compNameEn: 'southward intl logistics ltd.',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007697,
    version: 10,
    compNameEn: 'Los Angeles Limited Technology',
    countryId: 167,
    cityId: 3609,
    cityNameCn: '纽约',
    cityNameEn: 'New York',
    countryNameCn: '美国',
    countryNameEn: 'United States',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007747,
    version: 9,
    compNameEn: 'wybtest',
    countryId: 68,
    cityId: 101,
    cityNameCn: '迪拜',
    cityNameEn: 'Dubai',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 2057668,
    version: 12,
    compNameCn: '浙江中外运有限公司宁波明州分公司',
    compNameEn: 'SINOTRANS ZHEJIANG CO.,LTD. NINGBO MINGZHOU BRANCH',
    countryId: 1,
    cityId: 2768,
    cityNameCn: '宁波',
    cityNameEn: 'Ningbo',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 192,
    relSaleName: '刘帅(Brook)',
    belongDepartmentId: 44,
    belongDepartmentName: '国内销售三部',
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3008252,
    version: 8,
    compNameCn: '大连其味无穷恶趣味',
    compNameEn: 'hwreg28 comp',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 307,
    relSaleName: 'admin3',
    belongDepartmentId: 20,
    belongDepartmentName: '测试组',
    customerId: 310,
    customerName: 'admin6-ldy(ldy)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008646,
    version: 1,
    compNameCn: '入到算有限责任公司',
    compNameEn: 'jiao202306090928',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008647,
    version: 2,
    compNameCn: '实些红有限责任公司',
    compNameEn: 'jiao202306090954',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008650,
    version: 3,
    compNameCn: '各化音有限责任公司',
    compNameEn: 'jiao202306091034',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008656,
    version: 1,
    compNameEn: 'jiao202306090337',
    countryId: 51,
    cityId: 14,
    cityNameCn: '阿尔及尔',
    cityNameEn: 'Algiers',
    countryNameCn: '阿尔及利亚',
    countryNameEn: 'Algeria',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008721,
    version: 1,
    compNameCn: 'adsfasfdsaf',
    compNameEn: 'adsfasfdsaf',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 333,
    customerName: '测试账号_llj(TEST_LLJ)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 1000052,
    version: 9,
    compNameCn: 'Precision Shipping Inc.',
    compNameEn: 'Test123',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000017,
    version: 25,
    compNameCn: '广州润通国际货运有限公司深圳分公司',
    countryId: 1,
    cityId: 2882,
    cityNameCn: '深圳',
    cityNameEn: 'Shenzhen',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000019,
    version: 20,
    compNameCn: '上海盟捷国际货运有限公司',
    compNameEn: 'ShanghaiJiemnghuoyun1111',
    countryId: 1,
    cityId: 2668,
    cityNameCn: '秦皇岛',
    cityNameEn: 'Qinhuangdao',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008371,
    version: 6,
    compNameCn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    compNameEn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    countryId: 149,
    cityId: 538,
    cityNameCn: '汉堡',
    cityNameEn: 'Hamburg',
    countryNameCn: '德国',
    countryNameEn: 'Germany',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000319,
    version: 16,
    compNameEn: 'Farway Express International Logistics (Shanghai) Co.,Ltd',
    countryId: 145,
    cityId: 329,
    cityNameCn: '安特卫普',
    cityNameEn: 'Antwerp',
    countryNameCn: '比利时',
    countryNameEn: 'Belgium',
    relSaleId: 160,
    relSaleName: '许娜(Freya)',
    belongDepartmentId: 40,
    belongDepartmentName: '海外销售四部二组',
    customerId: 277,
    customerName: '王鹤曈(teresa)',
    customerDepartmentId: 27,
    customerDepartmentName: '海外客户成功部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007441,
    version: 17,
    compNameCn: 'ceshi999公司',
    compNameEn: 'ceshi999',
    countryId: 1,
    cityId: 2667,
    cityNameCn: '唐山',
    cityNameEn: 'Tangshan',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008291,
    version: 24,
    compNameEn: 'Atlanta',
    countryId: 68,
    cityId: 99,
    cityNameCn: '阿布扎比',
    cityNameEn: 'Abu Dhabi',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000135,
    version: 38,
    compNameCn: '深圳市中技物流有限公司',
    compNameEn: 'Sinotech Logistics Co.,Ltd.',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 200,
    relSaleName: '蒙文雅',
    belongDepartmentId: 42,
    belongDepartmentName: '国内销售二区',
    customerId: 178,
    customerName: '翁婷婷',
    customerDepartmentId: 28,
    customerDepartmentName: '国内会员服务部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1004187,
    version: 15,
    compNameCn: '上海邦达天原货运有限公司芜湖分公司',
    compNameEn: 'Shanghai Air Sea Transport Inc. Wuhu Branch Ltd.',
    countryId: 1,
    cityId: 2779,
    cityNameCn: '芜湖',
    cityNameEn: 'Wuhu',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007362,
    version: 51,
    compNameCn: '中文公司',
    compNameEn: 'jiekou0',
    countryId: 2,
    cityId: 315,
    cityNameCn: '阿黎博里',
    cityNameEn: 'Alibori',
    countryNameCn: '贝宁',
    countryNameEn: 'Benin',
    relSaleId: 297,
    relSaleName: '李小鑫',
    belongDepartmentId: 43,
    belongDepartmentName: '国内销售一部',
    customerId: 265,
    customerName: '张彬',
    customerDepartmentId: 44,
    customerDepartmentName: '国内销售三部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000929,
    version: 7,
    compNameEn: 'southward intl logistics ltd.',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007697,
    version: 10,
    compNameEn: 'Los Angeles Limited Technology',
    countryId: 167,
    cityId: 3609,
    cityNameCn: '纽约',
    cityNameEn: 'New York',
    countryNameCn: '美国',
    countryNameEn: 'United States',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007747,
    version: 9,
    compNameEn: 'wybtest',
    countryId: 68,
    cityId: 101,
    cityNameCn: '迪拜',
    cityNameEn: 'Dubai',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 2057668,
    version: 12,
    compNameCn: '浙江中外运有限公司宁波明州分公司',
    compNameEn: 'SINOTRANS ZHEJIANG CO.,LTD. NINGBO MINGZHOU BRANCH',
    countryId: 1,
    cityId: 2768,
    cityNameCn: '宁波',
    cityNameEn: 'Ningbo',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 192,
    relSaleName: '刘帅(Brook)',
    belongDepartmentId: 44,
    belongDepartmentName: '国内销售三部',
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3008252,
    version: 8,
    compNameCn: '大连其味无穷恶趣味',
    compNameEn: 'hwreg28 comp',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 307,
    relSaleName: 'admin3',
    belongDepartmentId: 20,
    belongDepartmentName: '测试组',
    customerId: 310,
    customerName: 'admin6-ldy(ldy)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008646,
    version: 1,
    compNameCn: '入到算有限责任公司',
    compNameEn: 'jiao202306090928',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008647,
    version: 2,
    compNameCn: '实些红有限责任公司',
    compNameEn: 'jiao202306090954',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008650,
    version: 3,
    compNameCn: '各化音有限责任公司',
    compNameEn: 'jiao202306091034',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008656,
    version: 1,
    compNameEn: 'jiao202306090337',
    countryId: 51,
    cityId: 14,
    cityNameCn: '阿尔及尔',
    cityNameEn: 'Algiers',
    countryNameCn: '阿尔及利亚',
    countryNameEn: 'Algeria',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008721,
    version: 1,
    compNameCn: 'adsfasfdsaf',
    compNameEn: 'adsfasfdsaf',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 333,
    customerName: '测试账号_llj(TEST_LLJ)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 1000052,
    version: 9,
    compNameCn: 'Precision Shipping Inc.',
    compNameEn: 'Test123',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000017,
    version: 25,
    compNameCn: '广州润通国际货运有限公司深圳分公司',
    countryId: 1,
    cityId: 2882,
    cityNameCn: '深圳',
    cityNameEn: 'Shenzhen',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000019,
    version: 20,
    compNameCn: '上海盟捷国际货运有限公司',
    compNameEn: 'ShanghaiJiemnghuoyun1111',
    countryId: 1,
    cityId: 2668,
    cityNameCn: '秦皇岛',
    cityNameEn: 'Qinhuangdao',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008371,
    version: 6,
    compNameCn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    compNameEn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    countryId: 149,
    cityId: 538,
    cityNameCn: '汉堡',
    cityNameEn: 'Hamburg',
    countryNameCn: '德国',
    countryNameEn: 'Germany',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000319,
    version: 16,
    compNameEn: 'Farway Express International Logistics (Shanghai) Co.,Ltd',
    countryId: 145,
    cityId: 329,
    cityNameCn: '安特卫普',
    cityNameEn: 'Antwerp',
    countryNameCn: '比利时',
    countryNameEn: 'Belgium',
    relSaleId: 160,
    relSaleName: '许娜(Freya)',
    belongDepartmentId: 40,
    belongDepartmentName: '海外销售四部二组',
    customerId: 277,
    customerName: '王鹤曈(teresa)',
    customerDepartmentId: 27,
    customerDepartmentName: '海外客户成功部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007441,
    version: 17,
    compNameCn: 'ceshi999公司',
    compNameEn: 'ceshi999',
    countryId: 1,
    cityId: 2667,
    cityNameCn: '唐山',
    cityNameEn: 'Tangshan',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008291,
    version: 24,
    compNameEn: 'Atlanta',
    countryId: 68,
    cityId: 99,
    cityNameCn: '阿布扎比',
    cityNameEn: 'Abu Dhabi',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000135,
    version: 38,
    compNameCn: '深圳市中技物流有限公司',
    compNameEn: 'Sinotech Logistics Co.,Ltd.',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 200,
    relSaleName: '蒙文雅',
    belongDepartmentId: 42,
    belongDepartmentName: '国内销售二区',
    customerId: 178,
    customerName: '翁婷婷',
    customerDepartmentId: 28,
    customerDepartmentName: '国内会员服务部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1004187,
    version: 15,
    compNameCn: '上海邦达天原货运有限公司芜湖分公司',
    compNameEn: 'Shanghai Air Sea Transport Inc. Wuhu Branch Ltd.',
    countryId: 1,
    cityId: 2779,
    cityNameCn: '芜湖',
    cityNameEn: 'Wuhu',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007362,
    version: 51,
    compNameCn: '中文公司',
    compNameEn: 'jiekou0',
    countryId: 2,
    cityId: 315,
    cityNameCn: '阿黎博里',
    cityNameEn: 'Alibori',
    countryNameCn: '贝宁',
    countryNameEn: 'Benin',
    relSaleId: 297,
    relSaleName: '李小鑫',
    belongDepartmentId: 43,
    belongDepartmentName: '国内销售一部',
    customerId: 265,
    customerName: '张彬',
    customerDepartmentId: 44,
    customerDepartmentName: '国内销售三部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000929,
    version: 7,
    compNameEn: 'southward intl logistics ltd.',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007697,
    version: 10,
    compNameEn: 'Los Angeles Limited Technology',
    countryId: 167,
    cityId: 3609,
    cityNameCn: '纽约',
    cityNameEn: 'New York',
    countryNameCn: '美国',
    countryNameEn: 'United States',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007747,
    version: 9,
    compNameEn: 'wybtest',
    countryId: 68,
    cityId: 101,
    cityNameCn: '迪拜',
    cityNameEn: 'Dubai',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 2057668,
    version: 12,
    compNameCn: '浙江中外运有限公司宁波明州分公司',
    compNameEn: 'SINOTRANS ZHEJIANG CO.,LTD. NINGBO MINGZHOU BRANCH',
    countryId: 1,
    cityId: 2768,
    cityNameCn: '宁波',
    cityNameEn: 'Ningbo',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 192,
    relSaleName: '刘帅(Brook)',
    belongDepartmentId: 44,
    belongDepartmentName: '国内销售三部',
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3008252,
    version: 8,
    compNameCn: '大连其味无穷恶趣味',
    compNameEn: 'hwreg28 comp',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 307,
    relSaleName: 'admin3',
    belongDepartmentId: 20,
    belongDepartmentName: '测试组',
    customerId: 310,
    customerName: 'admin6-ldy(ldy)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008646,
    version: 1,
    compNameCn: '入到算有限责任公司',
    compNameEn: 'jiao202306090928',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008647,
    version: 2,
    compNameCn: '实些红有限责任公司',
    compNameEn: 'jiao202306090954',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008650,
    version: 3,
    compNameCn: '各化音有限责任公司',
    compNameEn: 'jiao202306091034',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008656,
    version: 1,
    compNameEn: 'jiao202306090337',
    countryId: 51,
    cityId: 14,
    cityNameCn: '阿尔及尔',
    cityNameEn: 'Algiers',
    countryNameCn: '阿尔及利亚',
    countryNameEn: 'Algeria',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008721,
    version: 1,
    compNameCn: 'adsfasfdsaf',
    compNameEn: 'adsfasfdsaf',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 333,
    customerName: '测试账号_llj(TEST_LLJ)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 1000052,
    version: 9,
    compNameCn: 'Precision Shipping Inc.',
    compNameEn: 'Test123',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000017,
    version: 25,
    compNameCn: '广州润通国际货运有限公司深圳分公司',
    countryId: 1,
    cityId: 2882,
    cityNameCn: '深圳',
    cityNameEn: 'Shenzhen',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000019,
    version: 20,
    compNameCn: '上海盟捷国际货运有限公司',
    compNameEn: 'ShanghaiJiemnghuoyun1111',
    countryId: 1,
    cityId: 2668,
    cityNameCn: '秦皇岛',
    cityNameEn: 'Qinhuangdao',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008371,
    version: 6,
    compNameCn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    compNameEn: 'Qingdao Friendly-line International Freight Agency Co.,Ltd.',
    countryId: 149,
    cityId: 538,
    cityNameCn: '汉堡',
    cityNameEn: 'Hamburg',
    countryNameCn: '德国',
    countryNameEn: 'Germany',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000319,
    version: 16,
    compNameEn: 'Farway Express International Logistics (Shanghai) Co.,Ltd',
    countryId: 145,
    cityId: 329,
    cityNameCn: '安特卫普',
    cityNameEn: 'Antwerp',
    countryNameCn: '比利时',
    countryNameEn: 'Belgium',
    relSaleId: 160,
    relSaleName: '许娜(Freya)',
    belongDepartmentId: 40,
    belongDepartmentName: '海外销售四部二组',
    customerId: 277,
    customerName: '王鹤曈(teresa)',
    customerDepartmentId: 27,
    customerDepartmentName: '海外客户成功部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007441,
    version: 17,
    compNameCn: 'ceshi999公司',
    compNameEn: 'ceshi999',
    countryId: 1,
    cityId: 2667,
    cityNameCn: '唐山',
    cityNameEn: 'Tangshan',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3008291,
    version: 24,
    compNameEn: 'Atlanta',
    countryId: 68,
    cityId: 99,
    cityNameCn: '阿布扎比',
    cityNameEn: 'Abu Dhabi',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1000135,
    version: 38,
    compNameCn: '深圳市中技物流有限公司',
    compNameEn: 'Sinotech Logistics Co.,Ltd.',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 200,
    relSaleName: '蒙文雅',
    belongDepartmentId: 42,
    belongDepartmentName: '国内销售二区',
    customerId: 178,
    customerName: '翁婷婷',
    customerDepartmentId: 28,
    customerDepartmentName: '国内会员服务部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 1004187,
    version: 15,
    compNameCn: '上海邦达天原货运有限公司芜湖分公司',
    compNameEn: 'Shanghai Air Sea Transport Inc. Wuhu Branch Ltd.',
    countryId: 1,
    cityId: 2779,
    cityNameCn: '芜湖',
    cityNameEn: 'Wuhu',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 3007362,
    version: 51,
    compNameCn: '中文公司',
    compNameEn: 'jiekou0',
    countryId: 2,
    cityId: 315,
    cityNameCn: '阿黎博里',
    cityNameEn: 'Alibori',
    countryNameCn: '贝宁',
    countryNameEn: 'Benin',
    relSaleId: 297,
    relSaleName: '李小鑫',
    belongDepartmentId: 43,
    belongDepartmentName: '国内销售一部',
    customerId: 265,
    customerName: '张彬',
    customerDepartmentId: 44,
    customerDepartmentName: '国内销售三部',
    auditStatus: '2',
    url:
      'https://wlw-obs-dev-bj4n.obs.cn-north-4.myhuaweicloud.com:443/COMPANY_LOGO%2F6b8fe7b2-8710-4ede-8f21-41e61f18663c'
  },
  {
    id: 2000929,
    version: 7,
    compNameEn: 'southward intl logistics ltd.',
    countryId: 1,
    cityId: 4019,
    cityNameCn: '上海啊',
    cityNameEn: 'ShanghaiAAA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007697,
    version: 10,
    compNameEn: 'Los Angeles Limited Technology',
    countryId: 167,
    cityId: 3609,
    cityNameCn: '纽约',
    cityNameEn: 'New York',
    countryNameCn: '美国',
    countryNameEn: 'United States',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3007747,
    version: 9,
    compNameEn: 'wybtest',
    countryId: 68,
    cityId: 101,
    cityNameCn: '迪拜',
    cityNameEn: 'Dubai',
    countryNameCn: '阿联酋',
    countryNameEn: 'United Arab Emirates',
    belongDepartmentId: -1,
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 2057668,
    version: 12,
    compNameCn: '浙江中外运有限公司宁波明州分公司',
    compNameEn: 'SINOTRANS ZHEJIANG CO.,LTD. NINGBO MINGZHOU BRANCH',
    countryId: 1,
    cityId: 2768,
    cityNameCn: '宁波',
    cityNameEn: 'Ningbo',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 192,
    relSaleName: '刘帅(Brook)',
    belongDepartmentId: 44,
    belongDepartmentName: '国内销售三部',
    customerDepartmentId: -1,
    auditStatus: '1'
  },
  {
    id: 3008252,
    version: 8,
    compNameCn: '大连其味无穷恶趣味',
    compNameEn: 'hwreg28 comp',
    countryId: 1,
    cityId: 2666,
    cityNameCn: '石家庄',
    cityNameEn: 'ShijiazhuangA',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 307,
    relSaleName: 'admin3',
    belongDepartmentId: 20,
    belongDepartmentName: '测试组',
    customerId: 310,
    customerName: 'admin6-ldy(ldy)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008646,
    version: 1,
    compNameCn: '入到算有限责任公司',
    compNameEn: 'jiao202306090928',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008647,
    version: 2,
    compNameCn: '实些红有限责任公司',
    compNameEn: 'jiao202306090954',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008650,
    version: 3,
    compNameCn: '各化音有限责任公司',
    compNameEn: 'jiao202306091034',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa(owen)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008656,
    version: 1,
    compNameEn: 'jiao202306090337',
    countryId: 51,
    cityId: 14,
    cityNameCn: '阿尔及尔',
    cityNameEn: 'Algiers',
    countryNameCn: '阿尔及利亚',
    countryNameEn: 'Algeria',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 328,
    customerName: '焦延鑫aaa',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  },
  {
    id: 3008721,
    version: 1,
    compNameCn: 'adsfasfdsaf',
    compNameEn: 'adsfasfdsaf',
    countryId: 1,
    cityId: 2701,
    cityNameCn: '大连',
    cityNameEn: 'Dalian',
    countryNameCn: '中国',
    countryNameEn: 'China',
    relSaleId: 429,
    relSaleName: '焦延鑫111',
    belongDepartmentId: 60,
    belongDepartmentName: '测试',
    customerId: 333,
    customerName: '测试账号_llj(TEST_LLJ)',
    customerDepartmentId: 20,
    customerDepartmentName: '测试组',
    auditStatus: '0'
  }
];
